name: Kick the Sheets
include:
  - signingConfig.yml
options:
  deploymentTarget: "16.0"
  bundleIdPrefix: com.ayrenking
packages:
  SQLite:
    url: https://github.com/stephencelis/SQLite.swift.git
    branch: master
targets:
  KTS:
    type: application
    platform: iOS
    sources: ["Kick the Sheets"]
    settings:
      base:
        INFOPLIST_FILE: Kick the Sheets/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.ayrenking.Kick-the-Sheets
        PRODUCT_NAME: KTS
        CURRENT_PROJECT_VERSION: 3
        MARKETING_VERSION: 2
        PRODUCT_MODULE_NAME: KTS
    dependencies:
      - framework: Services.framework
      - framework: Shared.framework
      - target: DailyProgressWidget
  
  Services:
    type: framework
    platform: iOS
    sources: [Services]
    settings:
      configs:
    dependencies:
      - package: SQLite

  Shared:
    type: framework
    platform: iOS
    sources: [Shared]
    settings:
      configs:
    dependencies:
      - framework: Services.framework

  
  KTSTests:
    type: bundle.unit-test
    platform: iOS
    sources: ["Kick the SheetsTests"]
    settings:
      configs:
    dependencies:
      - target: KTS
        type: regular
        optional: true
      - package: SQLite
        type: regular
        optional: true

  KTSUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "16.0"
    sources: ["Kick the SheetsUITests"]
    settings:
      configs:
    dependencies:
      - target: KTS
        type: regular
        optional: true
      - package: SQLite
        type: regular
        optional: true

  DailyProgressWidget:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    sources: [DailyProgressWidget]
    settings:
      configs:
    dependencies:
      - framework: Services.framework
      - framework: Shared.framework
      