name: iOS CI/CD

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  Test:
    name: Run Unit Tests
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      
      - name: Install Fastlane
        run: gem install fastlane -NV

      - name: Run Unit Tests
        run: fastlane scan --scheme "Kick the Sheets" --clean
        env:
          TERM: xterm-256color