name: iOS CI/CD

on: [push]

jobs:
  Test:
    name: Unit & UI Tests
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      
      - name: Install Fastlane
        run: gem install fastlane -NV

      - name: Install XcodeGen
        uses: xavierLowmiller/xcodegen-action@1.1.2
        with:
          spec: project.yml
          quiet: true
          version: 'latest'
      

      - name: Run Tests
        run: |
          echo "Running Unit Tests"
          cd "Kick the Sheets"
          fastlane scan --clean
          echo "Tests Complete"
        env:
          TERM: xterm-256color
