name: iOS CI/CD

on: [push]

jobs:
  Test:
    name: Unit Tests
    runs-on: macos-latest

    steps:
      - name: List Xcode installations
        run: sudo ls -1 /Applications | grep "Xcode"

      - name: Select Xcode 15.1
        run: sudo xcode-select -s /Applications/Xcode_15.1.app/Contents/Developer

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      
      - name: Install Fastlane
        run: gem install fastlane -NV

      - name: Install XcodeGen
        uses: xavierLowmiller/xcodegen-action@1.1.2
        with:
          spec: project.yml
          quiet: true
          version: 'latest'
      

      - name: Run Tests
        run: |
          echo "Running Unit Tests"
          fastlane scan --scheme "Debug" --clean
          echo "Tests Complete"
        env:
          TERM: xterm-256color
